spring.application.name=price-tracker

# Cofre de Integracao do Telegram
telegram.bot.token=8708403055:AAEFpHVyoSQU6gqp_QwEJQV6dbvNVvpN-40
telegram.bot.chat-id=7354596050

# Conexao com o Banco de Dados (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tracker_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:KigxgW044#A1}

# Desativar a criacao automatica do Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Cofre do Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
